-- Import tags from HighLevel CSV export
-- Run this in the Supabase SQL Editor (bypasses RLS)

-- 1. Create all unique tags
INSERT INTO tags (name) VALUES
  ('ni'),
  ('new unopened'),
  ('unsubscribed'),
  ('bounced'),
  ('opened'),
  ('delivered'),
  ('clicked'),
  ('clicked new'),
  ('clicked old'),
  ('active')
ON CONFLICT (name) DO NOTHING;

-- 2. Assign tags to contacts matched by email
INSERT INTO contact_tags (contact_id, tag_id)
SELECT c.id, t.id
FROM (VALUES
  ('info@graepels.com', 'ni'),
  ('info@graepels.com', 'new unopened'),
  ('alan@kageengineering.co.uk', 'ni'),
  ('alan@kageengineering.co.uk', 'new unopened'),
  ('info@a-c-technology.com', 'ni'),
  ('info@a-c-technology.com', 'new unopened'),
  ('info@moyfabtool.com', 'ni'),
  ('info@moyfabtool.com', 'new unopened'),
  ('general@rjsmythengineering.com', 'ni'),
  ('general@rjsmythengineering.com', 'new unopened'),
  ('info@daanengineering.com', 'ni'),
  ('info@daanengineering.com', 'new unopened'),
  ('sales@fastprofilecut.com', 'ni'),
  ('sales@fastprofilecut.com', 'new unopened'),
  ('brian@mulfabengineering.com', 'ni'),
  ('brian@mulfabengineering.com', 'new unopened'),
  ('sales@dmacengineering.com', 'ni'),
  ('sales@dmacengineering.com', 'unsubscribed'),
  ('john.currie@curriefabtech.co.uk', 'ni'),
  ('john.currie@curriefabtech.co.uk', 'new unopened'),
  ('info@jmsmetaltec.com', 'ni'),
  ('info@jmsmetaltec.com', 'new unopened'),
  ('info@ae-manufacturing.com', 'ni'),
  ('info@ae-manufacturing.com', 'new unopened'),
  ('stephen@dmlaser-fab.co.uk', 'ni'),
  ('stephen@dmlaser-fab.co.uk', 'new unopened'),
  ('sales@kme-steelworks.com', 'ni'),
  ('sales@kme-steelworks.com', 'new unopened'),
  ('neil@norwestengineering.co.uk', 'new unopened'),
  ('sales@barrington-metalworks.co.uk', 'new unopened'),
  ('info@a-tech.uk.com', 'new unopened'),
  ('sales@mwamspecialistengineers.co.uk', 'new unopened'),
  ('reveriemetalco@gmail.com', 'new unopened'),
  ('sales@pointeng.com', 'new unopened'),
  ('sales@elbmetalworks.com', 'new unopened'),
  ('enquiries@lpfabrication.co.uk', 'new unopened'),
  ('sales@rrengineering.com', 'new unopened'),
  ('mail@play-scheme.co.uk', 'new unopened'),
  ('appliedlasersolutionsltd@gmail.com', 'new unopened'),
  ('info@tockwithprofiles.co.uk', 'new unopened'),
  ('sales@enterprise-uk.co.uk', 'new unopened'),
  ('info@akstainlessltd.co.uk', 'new unopened'),
  ('info@zzenengineering.co.uk', 'new unopened'),
  ('admin@jsr-engineers.co.uk', 'bounced'),
  ('sales@sjs-laser.co.uk', 'new unopened'),
  ('info@scstaintech.co.uk', 'new unopened'),
  ('info@woldsworkshop.co.uk', 'new unopened'),
  ('sales@harveyfabrication.com', 'new unopened'),
  ('info@mondrelog.com', 'new unopened'),
  ('sales@metalworldeng.com', 'new unopened'),
  ('info@pss-uk.com', 'new unopened'),
  ('liamevans@akbryanmoulds.com', 'new unopened'),
  ('sales@ecam.co.uk', 'new unopened'),
  ('sales@plcomponents.co.uk', 'unsubscribed'),
  ('sales@kmf.co.uk', 'new unopened'),
  ('sales@dvmachining.co.uk', 'new unopened'),
  ('sales@jsjengineering.co.uk', 'new unopened'),
  ('designs@heycreate.co.uk', 'new unopened'),
  ('niki@hbhumphries.co.uk', 'new unopened'),
  ('sales@bdeltd.co.uk', 'new unopened'),
  ('sales@awbl.co.uk', 'new unopened'),
  ('sales@c3engineering.co.uk', 'new unopened'),
  ('info@tbi.uk.com', 'new unopened'),
  ('info@dalesheetmetal.com', 'new unopened'),
  ('sales@laserfast.co.uk', 'new unopened'),
  ('sales@peakeproducts.co.uk', 'new unopened'),
  ('info@campbellgrindlayengineering.com', 'bounced'),
  ('contact@mslaserservices.co.uk', 'new unopened'),
  ('sales@jienco.co.uk', 'new unopened'),
  ('sales@mh-eng.co.uk', 'new unopened'),
  ('info@tailoredlaser.com', 'new unopened'),
  ('info@sde.technology', 'new unopened'),
  ('sales@ssfltd.uk', 'new unopened'),
  ('sales@hollinbrow.co.uk', 'new unopened'),
  ('sales@deltasheetmetal.co.uk', 'bounced'),
  ('sales@foil-specialists.co.uk', 'new unopened'),
  ('sales@sysclad.co.uk', 'new unopened'),
  ('sales@fabtechltd.co.uk', 'new unopened'),
  ('sales@cimtek.co.uk', 'new unopened'),
  ('cb@epicfabs.co.uk', 'new unopened'),
  ('info@precision-metals.co.uk', 'new unopened'),
  ('sales@cumbriaprofiling.co.uk', 'new unopened'),
  ('sales@arclasercutnfab.co.uk', 'new unopened'),
  ('info@kgmlaser.co.uk', 'new unopened'),
  ('sales@yorkshireprofiles.co.uk', 'new unopened'),
  ('info@titchfieldgroup.com', 'new unopened'),
  ('info@bandzmetalcraft.co.uk', 'unsubscribed'),
  ('sales@dswilletts.co.uk', 'opened'),
  ('enquiries@metaloffcuts.co.uk', 'delivered'),
  ('enquiries@metaloffcuts.co.uk', 'bounced'),
  ('info@hurfar.co.uk', 'delivered'),
  ('enquiries@southernlasercutting.com', 'delivered'),
  ('sales@yorgrip.co.uk', 'delivered'),
  ('sales@nsigroup.co.uk', 'opened'),
  ('sales@phoenixlaser.co.uk', 'delivered'),
  ('sales@mhlaser.co.uk', 'delivered'),
  ('sales@aemsteelprofiles.co.uk', 'opened'),
  ('sales@lakelandlaser.co.uk', 'delivered'),
  ('sales@laser-web.co.uk', 'delivered'),
  ('sales@hlt.co.uk', 'clicked'),
  ('sales@hlt.co.uk', 'clicked new'),
  ('sales@mplaser.co.uk', 'opened'),
  ('sales@laserprofiling.net', 'unsubscribed'),
  ('sales@fabtechsheetmetal.co.uk', 'delivered'),
  ('sales@win-all.co.uk', 'delivered'),
  ('spsales@sparta.co.uk', 'delivered'),
  ('info@wrightform.com', 'clicked'),
  ('info@wrightform.com', 'clicked new'),
  ('sales@congletonlaser.co.uk', 'delivered'),
  ('info@ashfordlasers.co.uk', 'opened'),
  ('enquiries@dragonlaser.co.uk', 'clicked'),
  ('enquiries@dragonlaser.co.uk', 'clicked new'),
  ('sales@acornlaser.co.uk', 'delivered'),
  ('info@hutchinson-engineering.co.uk', 'clicked'),
  ('info@hutchinson-engineering.co.uk', 'clicked new'),
  ('production@cymarc.co.uk', 'delivered'),
  ('sales@westgatestainless.com', 'clicked'),
  ('sales@westgatestainless.com', 'clicked new'),
  ('sales@acsteels.co.uk', 'delivered'),
  ('info@formwork.co.uk', 'delivered'),
  ('info@gps-limited.com', 'opened'),
  ('sales@harrissteels.co.uk', 'opened'),
  ('sales@techworx.co.uk', 'delivered'),
  ('sales@isteelfabrications.co.uk', 'opened'),
  ('info@midaslaser.co.uk', 'delivered'),
  ('sales@esplaser.com', 'delivered'),
  ('enquiries@dvsf.co.uk', 'delivered'),
  ('sales@simmal.co.uk', 'delivered'),
  ('sales@stevegrahamsales.com', 'clicked'),
  ('sales@stevegrahamsales.com', 'clicked new'),
  ('weld@jsteel.uk', 'delivered'),
  ('bridge@bridgefabs.com', 'delivered'),
  ('sales@randdsheetmetal.co.uk', 'delivered'),
  ('customer-service@macstrucks.co.uk', 'delivered'),
  ('enquiries@taylorbrosltd.co.uk', 'delivered'),
  ('sales@allsops.co.uk', 'opened'),
  ('laura@winfieldengineering.com', 'clicked'),
  ('laura@winfieldengineering.com', 'clicked new'),
  ('sales@premierlasertube.co.uk', 'opened'),
  ('info@yorkshirelaser.co.uk', 'delivered'),
  ('enquiries@jacksonsfabs.co.uk', 'delivered'),
  ('info@pas-engineering.co.uk', 'opened'),
  ('info@pcfabrications.com', 'opened'),
  ('sales@appliedmetal.co.uk', 'opened'),
  ('info@orangeboxfinishing.co.uk', 'clicked'),
  ('info@orangeboxfinishing.co.uk', 'clicked new'),
  ('admin@pembrokeshireengineering.co.uk', 'delivered'),
  ('info@primafabrications.co.uk', 'opened'),
  ('info@precisionmicro.com', 'clicked'),
  ('info@precisionmicro.com', 'clicked new'),
  ('sales@lubetengineering.com', 'opened'),
  ('office@powersystempartners.com', 'clicked'),
  ('office@powersystempartners.com', 'clicked new'),
  ('info@anengineering.co.uk', 'delivered'),
  ('sales@themetalstore.co.uk', 'delivered'),
  ('info@pmfltd.co.uk', 'delivered'),
  ('sales@cuttingedgelaser.co.uk', 'clicked'),
  ('sales@cuttingedgelaser.co.uk', 'clicked new'),
  ('info@coreengineering.co.uk', 'opened'),
  ('enquiries@kingsward.co.uk', 'clicked'),
  ('enquiries@kingsward.co.uk', 'clicked new'),
  ('sales@apsm.co.uk', 'delivered'),
  ('curt@kmshardrange.co.uk', 'delivered'),
  ('sales@prolaserltd.co.uk', 'delivered'),
  ('swelco@altron.co.uk', 'delivered'),
  ('enquiries@laserlabwales.com', 'delivered'),
  ('weldingcapacity@btconnect.com', 'delivered'),
  ('subcon@lister.co.uk', 'delivered'),
  ('steveb@lpegroup.uk', 'opened'),
  ('sales@rmfabrications.com', 'clicked'),
  ('sales@rmfabrications.com', 'clicked new'),
  ('sales@q-laser.co.uk', 'delivered'),
  ('sales@marlboroughltd.com', 'delivered'),
  ('sales@lasermaster.co.uk', 'delivered'),
  ('sales@gflaser.co.uk', 'delivered'),
  ('sales@esprecision.co.uk', 'opened'),
  ('sales@countyfabrications.co.uk', 'clicked'),
  ('sales@countyfabrications.co.uk', 'clicked new'),
  ('sales@broxton.com', 'delivered'),
  ('sales@bpfabs.co.uk', 'delivered'),
  ('sales@active-engineering.co.uk', 'delivered'),
  ('sales@abturnkey.co.uk', 'opened'),
  ('production@cncpunching.co.uk', 'clicked'),
  ('production@cncpunching.co.uk', 'clicked new'),
  ('office@dalta.co.uk', 'delivered'),
  ('nilesh@dalta.co.uk', 'delivered'),
  ('joe@brightonlaser.com', 'delivered'),
  ('jeremy.birch@leicsengineering.co.uk', 'delivered'),
  ('jack@jacknicholasgroup.co.uk', 'opened'),
  ('info@yorkshirecuttingcompany.com', 'clicked'),
  ('info@yorkshirecuttingcompany.com', 'clicked new'),
  ('info@xometry.uk', 'opened'),
  ('info@subconlaser.co.uk', 'delivered'),
  ('info@rclaserworks.co.uk', 'delivered'),
  ('info@promex.co.uk', 'delivered'),
  ('info@masterscnc.co.uk', 'opened'),
  ('info@mainemachining.com', 'delivered'),
  ('info@laserengraveuk.com', 'delivered'),
  ('info@jcmetalworks.co.uk', 'delivered'),
  ('info@fentech.co', 'delivered'),
  ('info@davidrossfabrications.co.uk', 'delivered'),
  ('info@andoverlaser.co.uk', 'clicked'),
  ('info@andoverlaser.co.uk', 'clicked new'),
  ('hello@cutaboveuk.co.uk', 'delivered'),
  ('enquiries@regentengineers.co.uk', 'opened'),
  ('enquiries@gwalker-eng.co.uk', 'opened'),
  ('enquiries@flexxgenix.com', 'opened'),
  ('enquiries@blackrow.co.uk', 'clicked'),
  ('enquiries@blackrow.co.uk', 'clicked new'),
  ('enquiries@adlasercutting.co.uk', 'clicked'),
  ('enquiries@adlasercutting.co.uk', 'clicked new'),
  ('contactus@findtheneedle.co.uk', 'delivered'),
  ('arrow@lister.co.uk', 'delivered'),
  ('andy@sorb.co.uk', 'delivered'),
  ('ady@barnettandshaw.co.uk', 'opened'),
  ('sales@rdltechnologies.co.uk', 'opened'),
  ('sales@lilleker.co.uk', 'delivered'),
  ('info@delga.co.uk', 'opened'),
  ('enquiries@contractsengineering.com', 'delivered'),
  ('sales@tpsm.co.uk', 'clicked'),
  ('sales@tpsm.co.uk', 'clicked new'),
  ('info@24hreng.co.uk', 'delivered'),
  ('info@screencraft.co.uk', 'delivered'),
  ('ja@stratfordprecision.co.uk', 'opened'),
  ('sales@laser24.co.uk', 'opened'),
  ('info@midland-laser.co.uk', 'opened'),
  ('info@prolaserservices.co.uk', 'delivered'),
  ('mail@steadandwilkins.co.uk', 'delivered'),
  ('info@resurgem.co.uk', 'delivered'),
  ('hello@ctrlasers.co.uk', 'delivered'),
  ('info@mobileweldinglondon.co.uk', 'delivered'),
  ('info@lgm-eng.co.uk', 'opened'),
  ('info@ddkengineering.co.uk', 'delivered'),
  ('info@apollolasercutting.co.uk', 'opened'),
  ('info@elsfab.co.uk', 'unsubscribed'),
  ('sales@lasercutit.co.uk', 'clicked'),
  ('sales@lasercutit.co.uk', 'clicked new'),
  ('sales@pagsheetmetal.com', 'delivered'),
  ('northsales@hublebas.co.uk', 'clicked'),
  ('northsales@hublebas.co.uk', 'clicked new'),
  ('westsales@hublebas.co.uk', 'clicked'),
  ('westsales@hublebas.co.uk', 'clicked new'),
  ('glyn@tubebendform.co.uk', 'opened'),
  ('sales@highspeedlasers.co.uk', 'clicked'),
  ('sales@highspeedlasers.co.uk', 'clicked new'),
  ('info@laserboost.com', 'delivered'),
  ('support@geomiq.com', 'opened'),
  ('sales@staffslaser.co.uk', 'clicked'),
  ('sales@staffslaser.co.uk', 'clicked new'),
  ('info@mt-uk.com', 'opened'),
  ('sales@lsengineering.co.uk', 'clicked'),
  ('sales@lsengineering.co.uk', 'clicked new'),
  ('sales@exactlasercutting.co.uk', 'clicked'),
  ('sales@exactlasercutting.co.uk', 'clicked new'),
  ('info.uk@fractory.com', 'opened'),
  ('sales@bradfordlaser.com', 'clicked'),
  ('sales@bradfordlaser.com', 'clicked new'),
  ('info@prestige-fabrications.co.uk', 'delivered'),
  ('help@unicornsheetmetal.com', 'delivered'),
  ('sales@barrettsteel.com', 'delivered'),
  ('sales@jetcutit.com', 'clicked'),
  ('sales@jetcutit.com', 'clicked new'),
  ('davidsmith.fabsltd@gmail.com', 'opened'),
  ('deaneliteengraving@gmail.com', 'opened'),
  ('sales@pure-plastics.co.uk', 'delivered'),
  ('uwebusiness@uwe.ac.uk', 'clicked'),
  ('uwebusiness@uwe.ac.uk', 'clicked new'),
  ('sales@mjpatch.co.uk', 'clicked'),
  ('sales@hocklynn.co.uk', 'opened'),
  ('info@tinycuts.net', 'delivered'),
  ('info@processdevelopment.co.uk', 'opened'),
  ('dave@lwjenkins.co.uk', 'opened'),
  ('sales@lightninglaser.co.uk', 'clicked'),
  ('sales@lightninglaser.co.uk', 'clicked new'),
  ('dan.taylor@avonmouthsigns.com', 'opened'),
  ('hello@gshedstudio.com', 'delivered'),
  ('info@frwarren.co.uk', 'opened'),
  ('sales@smiths1972.co.uk', 'delivered'),
  ('info@bristolcreatives.co.uk', 'opened'),
  ('sales@laserit.co.uk', 'delivered'),
  ('sales@formrite.uk', 'delivered'),
  ('sales@premierlaser.co.uk', 'delivered'),
  ('sales@fchammonds.co.uk', 'opened'),
  ('hello@bristoldesignforge.co.uk', 'opened'),
  ('sales@grailengineering.co.uk', 'delivered'),
  ('info@xtraweldservices.com', 'delivered'),
  ('enquiries@wmspence.co.uk', 'delivered'),
  ('sales@tneltd.com', 'delivered'),
  ('sales@lasercutting.co.uk', 'delivered'),
  ('sales@steelgram.co.uk', 'delivered'),
  ('sales@starweld.co.uk', 'delivered'),
  ('sales@specialistmetalfabrications.co.uk', 'delivered'),
  ('sales@sevenhillsfabrication.com', 'delivered'),
  ('parts@scottsuk.com', 'unsubscribed'),
  ('enquiries@salfordengineering.co.uk', 'delivered'),
  ('sales@rochfordengineering.co.uk', 'delivered'),
  ('sales@rmifab.co.uk', 'delivered'),
  ('sales@rdmoore.com', 'opened'),
  ('sales@qualitetch.com', 'delivered'),
  ('pjprojectsfabs@gmail.com', 'delivered'),
  ('tony@parkwayfabrications.co.uk', 'delivered'),
  ('info@parjacks.com', 'delivered'),
  ('sales@nu-gears.com', 'delivered'),
  ('sales@normesh.co.uk', 'delivered'),
  ('sales@mtplaser.co.uk', 'opened'),
  ('mfabssteel@gmail.com', 'delivered'),
  ('info@madeinsheffield.org', 'delivered'),
  ('sales@mtechengineering.co.uk', 'opened'),
  ('info@liontek.co.uk', 'opened'),
  ('sales@laser-online.co.uk', 'opened'),
  ('sales@laser.co.uk', 'delivered'),
  ('sales@laserexp.co.uk', 'opened'),
  ('sales@lasercentreuk.co.uk', 'opened'),
  ('info@knoxfordfabrications.co.uk', 'opened'),
  ('sales@kirmell.co.uk', 'delivered'),
  ('enquiries@jgbsteelcraft.co.uk', 'delivered'),
  ('enquiries@jtekengineering.co.uk', 'opened'),
  ('enquiries@intersealuk.co.uk', 'delivered'),
  ('sales@hfabs.co.uk', 'delivered'),
  ('sales@hucknallsheetmtl.co.uk', 'delivered'),
  ('sales@harrisonslasertech.co.uk', 'opened'),
  ('lee@hamiltonfab.co.uk', 'delivered'),
  ('sales@greengatemetal.co.uk', 'delivered'),
  ('info@framosfabrications.co.uk', 'delivered'),
  ('sales@femltd.co.uk', 'delivered'),
  ('enquiries@fclaser.co.uk', 'delivered'),
  ('sales@exactprecision.co.uk', 'unsubscribed'),
  ('sales@etmblades.com', 'delivered'),
  ('info@essentialfabrications.co.uk', 'delivered'),
  ('info@ekspan.com', 'delivered'),
  ('eastmidlandslaserfabs@gmail.com', 'opened'),
  ('daniel.mott291@btinternet.com', 'opened'),
  ('service@cut-tec.co.uk', 'delivered'),
  ('sales@curvecraft.com', 'opened'),
  ('enquiry@clieosupplies.com', 'delivered'),
  ('sales@daysteel.co.uk', 'delivered'),
  ('sales@chbarnett.co.uk', 'delivered'),
  ('info@cavaliersheetmetal.co.uk', 'opened'),
  ('enquiries@canhandling.com', 'delivered'),
  ('info@csfabs.co.uk', 'opened'),
  ('sales@arromax-engineering.co.uk', 'delivered'),
  ('mail@ai-fabrications.co.uk', 'opened'),
  ('sales@aetuk.com', 'delivered'),
  ('enquiry@adslaser.co.uk', 'clicked'),
  ('enquiry@adslaser.co.uk', 'clicked old'),
  ('sales@accurate-laser.co.uk', 'delivered'),
  ('sales@firstfabs.co.uk', 'opened'),
  ('wilkinsj@wolvcoll.ac.uk', 'clicked'),
  ('wilkinsj@wolvcoll.ac.uk', 'clicked old'),
  ('a.kyprianou@wmgacademy.org.uk', 'delivered'),
  ('k.knight@wmgacademy.org.uk', 'delivered'),
  ('ads@whitgift.co.uk', 'opened'),
  ('paulrowe@wessingtoncryogenics.com', 'delivered'),
  ('mike@utssalesandrepair.co.uk', 'opened'),
  ('jwevill@tubetekuk.com', 'opened'),
  ('chris@tlauk.net', 'clicked'),
  ('chris@tlauk.net', 'clicked old'),
  ('mattbingham@titansteelwheels.com', 'clicked'),
  ('mattbingham@titansteelwheels.com', 'clicked old'),
  ('dennis@spirewindows.com', 'opened'),
  ('chrisallwood@live.co.uk', 'delivered'),
  ('james.wooding@swale.at', 'delivered'),
  ('karl@storersltd.com', 'delivered'),
  ('sets@steelthescene.co.uk', 'clicked'),
  ('sets@steelthescene.co.uk', 'clicked old'),
  ('mat@starkandgreensmith.com', 'delivered'),
  ('gavin@stairformwork.co.uk', 'opened'),
  ('grahamw@swprocess.co.uk', 'active'),
  ('kristina.walsh@rca.ac.uk', 'delivered'),
  ('jamie@roseeng.co.uk', 'opened'),
  ('tom.kyte@rolls-royce.com', 'delivered'),
  ('paul.dearden@redshield.uk.com', 'delivered'),
  ('phil.richardson@polycrown.com', 'delivered'),
  ('dunstan_michael_j@perkins.com', 'clicked'),
  ('dunstan_michael_j@perkins.com', 'clicked old'),
  ('paul.oconnor@passengerliftsolutions.com', 'opened'),
  ('chris.smith@orionmis.co.uk', 'delivered'),
  ('info@nitrafabrication.co.uk', 'opened'),
  ('jack.stone144@mod.gov.uk', 'clicked'),
  ('jack.stone144@mod.gov.uk', 'clicked old'),
  ('john@mccannsgroup.com', 'delivered'),
  ('luke@innovatefabrication.co.uk', 'opened'),
  ('louis.clarke@envair.co.uk', 'opened'),
  ('terry.hughes@elmelin.com', 'clicked'),
  ('terry.hughes@elmelin.com', 'clicked old'),
  ('stuart@denward.com', 'delivered'),
  ('vbw@cld-fencing.com', 'clicked'),
  ('vbw@cld-fencing.com', 'clicked old'),
  ('jason@cflsteelservices.co.uk', 'opened'),
  ('joseph.douglas@cedlimited.com', 'opened'),
  ('hello@benchdogs.co.uk', 'opened'),
  ('michael@bakerthompson.co.uk', 'opened'),
  ('accounts@autospin.co.uk', 'delivered'),
  ('paul.jaggers@astonmartin.com', 'clicked'),
  ('paul.jaggers@astonmartin.com', 'clicked old'),
  ('rich@asdf.ltd', 'opened'),
  ('ams.steveg@gmail.com', 'opened'),
  ('andrew.steward@alsmechatronic.com', 'delivered'),
  ('bob@ajp-stainless.co.uk', 'delivered'),
  ('dave@abstractavr.com', 'delivered'),
  ('william.manners@a-tech.uk.com', 'opened'),
  ('sales@bcbinternational.co.uk', 'delivered'),
  ('sales@unicornsheetmetal.com', 'delivered'),
  ('laser@mejengineering.co.uk', 'delivered'),
  ('sales@pdssheetmetal.co.uk', 'delivered'),
  ('sales@victoriasheetmetal.com', 'delivered'),
  ('info@tek-neek.net', 'delivered'),
  ('sales@staffsfabs.co.uk', 'opened'),
  ('mail@rojaceng.com', 'unsubscribed'),
  ('sales@ritefab.co.uk', 'delivered'),
  ('sales@pkdsheetmetal.co.uk', 'delivered'),
  ('ms@norfran.co.uk', 'delivered'),
  ('info@needhamlaser.com', 'opened'),
  ('martin@mwfes.net', 'delivered'),
  ('midlandsmetalworks@gmail.com', 'opened'),
  ('sales@micrometric.co.uk', 'delivered'),
  ('sales@metalformseng.co.uk', 'delivered'),
  ('info@hendfab.com', 'delivered'),
  ('admin@harryburrows.co.uk', 'delivered'),
  ('sheetmetal@gsmvaltech.co.uk', 'delivered'),
  ('sales@grenville-engineering.co.uk', 'delivered'),
  ('gkrsheetmetal@outlook.com', 'opened'),
  ('sales@fsm.co.uk', 'delivered'),
  ('info@emsea.com', 'delivered'),
  ('sales@dmsstainless.co.uk', 'clicked'),
  ('sales@dmsstainless.co.uk', 'clicked old'),
  ('sales@dero.co.uk', 'opened'),
  ('sales@dmdesignfabrication.co.uk', 'delivered'),
  ('info@clarke-lane.co.uk', 'delivered'),
  ('info@bcfabrications.co.uk', 'delivered'),
  ('info@bcfabrications.co.uk', 'bounced'),
  ('enquiries@alpha1sml.co.uk', 'delivered'),
  ('sales@alcoeng.co.uk', 'delivered'),
  ('daniel.astarita@kesslers.com', 'clicked'),
  ('daniel.astarita@kesslers.com', 'clicked old'),
  ('luke@innovatefabrication.co.uk', 'opened'),
  ('rich@asdf.ltd', 'opened'),
  ('john@mccannsgroup.com', 'delivered'),
  ('sales@businessmagnet.co.uk', 'delivered'),
  ('sales@businessmagnet.co.uk', 'bounced'),
  ('alex@sousvidetools.com', 'delivered'),
  ('alex@gastronomyplus.com', 'delivered')
) AS v(email, tag_name)
JOIN contacts c ON LOWER(c.email) = LOWER(v.email)
JOIN tags t ON t.name = v.tag_name
ON CONFLICT (contact_id, tag_id) DO NOTHING;
